# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewUpdateMp3' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!
pod 'AFNetworking', '~> 3.1.0'
  # Pods for NewUpdateMp3

end
